### ISSUE TITLE
\begin{tabular}{lc} no longer working with last update

### ISSUE THREAD

**Issue by cryptohgb** [davidcarlisle/dpctex#52] opened 2024-06-14 11:41 UTC
The parameters l and c for the tabular environment are no longer working since the last update of the package in texlive 2024. It is still working in texlive 2023 which does not have the update of the colortbl package.
\begin{tabular}{cl}
...
\end{tabular}
throws an error "Undefinded control sequence ...<argument> \adl@dashcolor ..."

**Comment by davidcarlisle** [comment] 2024-06-14 11:50
If reporting issues please always provide a test file `\adl@dashcolor` does not appear in any files in this repository so the files here can not produce such an error. I would assume the command was intended to come from the `arydshln` package (which I do not maintain) but your un-shown document did not load that package but used its internal commands.

I'll close but you can re-open if you have a test file that only uses files from this repository.

**Comment by davidcarlisle** [comment] 2024-06-14 18:58
@cryptohgb  https://tex.stackexchange.com/a/720588/1090

**Comment by davidcarlisle** [comment] 2024-06-14 20:20
@cryptohgb a second answer proposes a possible fix, could you test this with your document thanks.

https://tex.stackexchange.com/a/720593/1090

**Comment by cryptohgb** [comment] 2024-06-15 07:59
That did it for me. Thx.

**Comment by shreeniwas-sapre** [comment] 2024-06-15 10:12
I had the same issue, and the fix above worked for me too.

**Comment by scottkosty** [comment] 2024-06-19 01:25
Just a note that I receive the same error for a document that uses Modern CV (https://ctan.org/pkg/moderncv?lang=en), which seems to load arydshln internally. Putting the code from the tex.se answer into the preamble makes the error go away.

**Comment by davidcarlisle** [comment] 2024-06-19 07:47
@scottkosty  thanks, I have contacted the package author but no response yet

**Comment by davidcarlisle** [comment] 2024-07-06 12:01
we have made a "firstaid" patch for arydashln so this problem should be fixed in current texlive releases, closing here.

**Closed as completed by davidcarlisle** 2024-07-06 12:01 UTC

**Comment by scottkosty** [comment] 2024-07-07 16:12
Perfect, thanks a lot David! Tested and works well. For anyone else who's curious, it took me a while to figure out that David literally meant the firstaid package. You can see the package here: https://ctan.org/pkg/latex-firstaid?lang=en, and the new version was released two weeks ago. You can also see arydashln detailed in the [package documentation](http://mirrors.ctan.org/macros/latex/required/firstaid/latex2e-first-aid-for-external-files.pdf).

**Comment by davidcarlisle** [comment] 2024-07-07 16:15
@scottkosty  sorry yes, I failed to make contact with the arydshln author so we added a firstaid, we'll remove it if the package gets updated,

**Comment by scottkosty** [comment] 2024-07-07 16:26
@davidcarlisle That makes a lot of sense! Thanks a lot for your time on all of this, even though the core issue wasn't your package's responsibility.

**Comment by scottkosty** [comment] 2024-07-26 01:50
I see what I think is the same issue when I use `pdflatex-dev`. Can anyone reproduce the issue with `pdflatex-dev`? Does it somehow not receive the firstaid update?

Possibly relevant version information:

```
$ pdflatex-dev '\stop'
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2024) (preloaded format=pdflatex-dev)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2024-11-01> patch level 1
L3 programming layer <2024-07-20>
No pages of output.
Transcript written on texput.log.
$ 
```
